### ISSUE TITLE
Access SPI Flash on the Video Kit

### ISSUE THREAD

**Issue by mannykoum** [infiniteorbits/polarfire-soc-video-kit-design#2]

**Comment by katia-katkat** [comment]
- [x] Obtain the correct Manufacturer and Device ID
- [x] Read and write to the SPI flash.
- [x] Run bitstream authentication.
- [x] Perform the auto-update feature.

**Comment by katia-katkat** [comment]
**Manufacturere/device ID + Read and write test** 
![image](https://github.com/infiniteorbits/polarfire-soc-video-kit-design/assets/83125186/9b9b004b-7072-4e66-b6c2-d0287bb7b37c)

**SPI FLASH Clients** 

![image](https://github.com/infiniteorbits/polarfire-soc-video-kit-design/assets/83125186/6a7b7215-4328-49b4-9a53-8040b2f4da03)


**Bitstream Authentification** 

**Auto_update feature test** 
After power cycling the board and running the design information : 

![image](https://github.com/infiniteorbits/polarfire-soc-video-kit-design/assets/83125186/ae12dc6e-526a-40d6-912d-9580f96c2206)

**IAP execution** 
After running the 5th command from the menu and power cycling the board : 
![image](https://github.com/infiniteorbits/polarfire-soc-video-kit-design/assets/83125186/2c89e6d8-76e6-4a60-add2-31a6ed9a6556)

**Comment by tiwari3101** [comment]
Verification steps: 

1. Used the FPGA job file available on https://github.com/infiniteorbits/polarfire-soc-video-kit-design/tree/SPI in the Readme.md to program the Video Kit. 
2. Cloned the repo(https://github.com/infiniteorbits/polarfire-soc-video-kit-design/) and switched to branch SPI. 
3. Imported the project 'mpfs-sys-serv' example under sw to SoftConsole. 
4. Built the project and flashed to the video kit using softconsole. 

The result is shown below: 


![Image](https://github.com/infiniteorbits/polarfire-soc-video-kit-design/assets/114018836/98918b88-86b0-40cc-978a-bdfee2f7fc0f)

Noted: 

1. The SPI Flash is enabled successsfully. 
2. The Device ID and the Manufacturer ID are read. 
3. The read-write test to the SPI Flash passes. 
4. The design information is obtained successfully.
